### ISSUE TITLE
Icloud Drive

### ISSUE THREAD

**Issue by vjrjunior** [jeremycastelli/Wordpress-new-project-config#11]
Hello, I'm trying to use by iCloud Drive, but the following message appears: 
line 11: /Users/name-user/Library/Mobile: No such file or directory.

The folder address I got is:
/Users/name-user/Library/Mobile Documents/com~apple~CloudDocs/

Do you have any idea how to solve this?
Thank you

**Comment by jeremycastelli** [comment]
Hey
The problem is the space, 
try to escape it with a backslash

DIRECTORY="/Users/name-user/Library/Mobile\ Documents/comappleCloudDocs/"

**Comment by vjrjunior** [comment]
Thanks for the reply, even so appeared error, attached follows the image of what happens:
![captura de tela 2017-04-06 as 16 22 43](https://cloud.githubusercontent.com/assets/11872954/24771835/7ae2b9c8-1ae5-11e7-930e-7af4a544a1be.png)

This was the address:
DIRECTORY="/Users/valdeirjunior/Library/Mobile\ Documents/com\~apple\~CloudDocs/SITES/"

**Comment by jeremycastelli** [comment]
Can you show me your config file please

**Comment by vjrjunior** [comment]
![captura de tela 2017-04-06 as 17 34 52](https://cloud.githubusercontent.com/assets/11872954/24774467/64cdf45e-1aef-11e7-98f5-f8170ea1716a.png)

**Comment by jeremycastelli** [comment]
try without the quotes

DIRECTORY=/Users/..../SITES/

**Comment by vjrjunior** [comment]
Same problem, I think I can not use any icloud drive :(

**Comment by jeremycastelli** [comment]
The problem is not icloud, this is the space
I see you are lauching the script from your working directory
This is not necessary, the script is made to be used globally and not per project.
you can put the script's folder anywhere on your hard drive
The DIRECTORY var is made for this, to specify where to install the new projects
try to move the script's folder on your desktop for a test

PS: in anyway it's not a good idea to put your code on an icloud drive
